"""
Simulated third-party Treatment/EMR module. A single pickle file holding one
binary-serialized blob — different again from the other four vendors (relational,
per-patient JSON files, key-value dbm, flat CSV). Mimics a legacy system that only
exposes a periodic binary data dump rather than a live query interface.

Only knows about treatment_local_id, never the hospital's canonical patient_id.

Note: pickle files are only ever read back here, generated by our own seed step —
never loaded from an untrusted source, so the usual pickle deserialization risk
doesn't apply.
"""
import pickle
from pathlib import Path

DB_PATH = Path(__file__).parent / "treatment_store.pkl"


def reset_and_seed(records_by_local_id: dict) -> int:
    with open(DB_PATH, "wb") as f:
        pickle.dump(records_by_local_id, f)
    return sum(len(recs) for recs in records_by_local_id.values())


def clear():
    if DB_PATH.exists():
        DB_PATH.unlink()


def _load() -> dict:
    if not DB_PATH.exists():
        return {}
    with open(DB_PATH, "rb") as f:
        return pickle.load(f)


def query_by_local_id(local_id: str) -> list[dict]:
    return _load().get(local_id, [])


def query_all() -> list[dict]:
    records = []
    for local_id, recs in _load().items():
        for r in recs:
            records.append({**r, "_local_id": local_id})
    return records
